apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-compactor-config
  namespace: ns-grafana
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3

    common:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - loki-distributor.ns-grafana.svc.cluster.local
        - loki-ingester.ns-grafana.svc.cluster.local
        - loki-query-frontend.ns-grafana.svc.cluster.local

    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
      retention_enabled: true

    schema_config:
      configs:
        - from: 2022-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
