apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-common-config
  namespace: ns-grafana
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_retain_period: 30s
      wal:
        enabled: true
        dir: /loki/wal

    frontend:
      scheduler_address: ""
      log_queries_longer_than: 5s
      compress_responses: true

    common:
      ring:
        kvstore:
          store: memberlist
      compactor_address: loki-compactor:9095

    query_scheduler:
      use_scheduler_ring: false


    frontend_worker:
      frontend_address: loki-query-frontend:9095

    memberlist:
      join_members:
        - loki-distributor.ns-grafana.svc.cluster.local
        - loki-ingester.ns-grafana.svc.cluster.local
        - loki-query-frontend.ns-grafana.svc.cluster.local

    schema_config:
      configs:
        - from: 2022-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_store_config:
      max_look_back_period: 0s
