---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-distributor
  namespace: ns-grafana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki-distributor
  template:
    metadata:
      labels:
        app: loki-distributor
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args: ["-config.file=/etc/loki/config.yaml", "-target=distributor"]
          ports:
            - name: http
              containerPort: 3100
            - name: grpc
              containerPort: 9095
            - name: memberlist
              containerPort: 7946
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-common-config
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data-pvc
