---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-compactor
  namespace: ns-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-compactor
  template:
    metadata:
      labels:
        app: loki-compactor
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args: ["-config.file=/etc/loki/config.yaml", "-target=compactor"]
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-compactor-config
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data-pvc
