---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-table-manager
  namespace: ns-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-table-manager
  template:
    metadata:
      labels:
        app: loki-table-manager
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args: ["-config.file=/etc/loki/config.yaml", "-target=table-manager"]
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-common-config
        - name: data
          emptyDir: {}
