---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-query-frontend
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-query-frontend
  template:
    metadata:
      labels:
        app: loki-query-frontend
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args: ["-config.file=/etc/loki/config.yaml", "-target=query-frontend"]
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
