apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
  namespace: ns-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Ukuran yang diminta untuk volume
  storageClassName: standard # Sesuaikan dengan storage class yang digunakan
