---
apiVersion: v1
kind: Service
metadata:
  name: loki-query-frontend
  namespace: observability
spec:
  type: LoadBalancer
  selector:
    app: loki-query-frontend
  ports:
    - name: http
      port: 3100
      targetPort: 3100
