apiVersion: v1
kind: Service
metadata:
  name: loki-distributor
  namespace: ns-grafana
spec:
  type: LoadBalancer # sesuaikan dengan kebutuhan kamu
  selector:
    app: loki-distributor # sesuaikan dengan label pod distributor kamu
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      targetPort: 9095
    - name: memberlist
      port: 7946
      targetPort: 7946
