apiVersion: v1
kind: Service
metadata:
  name: loki-ingester
  namespace: ns-grafana
spec:
  selector:
    app: loki-ingester # sesuaikan dengan label pod ingester kamu
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      targetPort: 9095
    - name: memberlist
      port: 7946
      targetPort: 7946
